export { default as CaretRightFilled } from './caret-right-filled'
export { default as FolderBlueMultiTone } from './folder-blue-multi-tone'
export { default as FolderOrangeMultiTone } from './folder-orange-multi-tone'
export { default as OverViewTwoTone } from './over-view-two-tone'
export { default as RightCircleTwoTone } from './right-circle-two-tone'
export { default as RightOutlined } from './right-outlined'
